### ISSUE TITLE
Sub Categories

### ISSUE THREAD

**Issue by McClainFocus** [tbdscripts/cosmo-issues#12]
**Describe the feature you'd like to see in Cosmo.**
Sub Categories like what u would see on Xenforo or mybb

**Give examples of the feature (screenshots, etc.). If applicable.**
https://imgur.com/f3vPzAs

**Are there any alternatives for this feature? If so, list them here.**
Not 100% sure

**Additional context**

**Comment by McClainFocus** [comment]
for the Forums btw

**Comment by Davidbp99** [comment]
https://gyazo.com/539589baae5e095950192ecc785b5ee3 https://gyazo.com/462a163590588297f6aef9750775edab

You can do this already.

Go to your management dashboard (cosmo) -> Boards -> make the stuff you need -> then drag accepted/denied (think that is what you are looking for) into the main board (player reports, ban appeals etc)
