### ISSUE TITLE
Havart theme custom color support (features icons)

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#14]
**Describe the feature you'd like to see in Cosmo.**
Add so the theme havart index icons features can be other colors than just default. Make it work like the other 3 themes where you select a color from the manager tabs. Then it will use that on the icons

**Give examples of the feature (screenshots, etc.). If applicable.**
https://gyazo.com/4520605174a63410a40b97d84294c36e (I self added this as I wanted it :D )

**Comment by Morgan-Moon** [comment]
The colour is got from the "Site Color" config within the dashboard. We do this for many reasons.. however, the main reason would be so that it goes along with the rest of the site. with it being the site colour.
