### ISSUE TITLE
Cosmo Chatbox (on forum+game servers)

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#15]
**Describe the feature you'd like to see in Cosmo.**
Forum Chat that connects to the ingame. So if someone would type /gc message (on rust or gmod). Then it would display something like [DarkRP] UserName: Hey guys. [Forum] UserName: Hey! . 

On the forum, they would just type to appear ingame (if a user gets banned on the forum they can't access the forum chat but can still do /gc unless they are muted ingame). 

The owner can define in cosmo what [Serveramazingname] would be displayed for the forum and servers. This could be done (some ideas)
A: cosmo_gmod/cosmo_rust to give the server the [AmazingServerChatName] and then the forum got the [forumsomethingname] that can be updated via manager panel.
B: everything is updated via the manager panel. Nothing in the cosmo_gmod or cosmo_rust to touch at all.

You can disable this if you don't want it or be auto disabled if the host can't have it (for some limits the host got )

**Give examples of the feature (screenshots, etc.). If applicable.**
https://gyazo.com/b3a3722340da691eace4ff34a196ef37

**Are there any alternatives for this feature? If so, list them here.**
Just a forum chat that is not connected to any game servers and no /gc message .

**Comment by mexdeloo** [comment]
I'm guessing you're talking about a chat box on the main forums view, like other forum software have. And the integration with game servers, so messages from web show up in-game and in-game messages show up in the web chatbox?

Maybe there needs to be some in-game command to toggle messaging to the web chatbox?
For example `!chat Hey web people`

And a command to toggle receiving messages from the web (in-game)

**Comment by Davidbp99** [comment]
@zeo yeah as some forum software got. Staffs (if they got the perms) can clear/remove messages from users. Just for cases when some spams it with the N word or something else that people don't want in the chats. 

Something like !chat or !gc (or even custom for server owners to set very easy).

But as well a way for a user self to opt out to not see the gc. As some just want to see the ooc/cooms and what is going on the server they play on. Not a global chat that says "OwO" in a very serious server :P

**Comment by LucaTanks** [comment]
It could be like a relay, similar to seen on Trixter’s and also a built in blocker of profanity that can be added to and edited from the admin page.

**Comment by mexdeloo** [comment]
Implemented in 1.5.0
