### ISSUE TITLE
Purity User Profile size problem

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#16]
**Describe the bug**
There are some scale issues with the user's avatar in the profile when you use Purity. It's fully normal if you got nothing in it.

**To Reproduce**
1. Go to theme Purity
2. Click on your profile (yourdomain.com/users/76561198072640553 )
3. Type something like me (or use an image just or bit of text): https://gyazo.com/cf2f7a66bfbe04018716249394bf8429 https://gyazo.com/edc9bf06d852b78ada84757a90eae0bd
4. See error. Your avatar will be width like 10% xD

**Expected behavior**
That the avatar logo would not be so small via the width.

**Screenshots**
(same screenshot as before)
https://gyazo.com/cf2f7a66bfbe04018716249394bf8429 
https://gyazo.com/edc9bf06d852b78ada84757a90eae0bd

**Comment by Morgan-Moon** [comment]
Should be fixed with the next public release!
