### ISSUE TITLE
Havart User Profile size problem

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#17]
**Describe the bug**
Like the purity report, I left. However, for this, it goes overflow past the box

**To Reproduce**
1. Go to theme Havart
2. Click on your profile (yourdomain.com/users/76561198072640553 )
3. Type something like me: https://gyazo.com/8c4e3e3b0084c24fd61bf962b7cdcd19
4. See error. The text goes woooooooooooooooooooooooooooooooooooooooooooooo past the thing.

**Expected behavior**
Instead of going past the box it should be moved down. Like this:

hey *box ends*
*Just below the text*
you

**Screenshots**
https://gyazo.com/8c4e3e3b0084c24fd61bf962b7cdcd19

**Comment by mexdeloo** [comment]
@Morgan-Moon Was this fixed?
