### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by Neko45** [tbdscripts/cosmo-issues#18]
**Describe the bug**
Spelling Mistake

**Error**
Says "This achievement was unlocked 1 day ago. Use is apart of our discord community"
instead of "This achievement was unlocked 1 day ago. UseR is apart of our discord community

**To Reproduce**
Setup Discord Sync, goto achievements

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/24734120/121535309-f470b980-c9f9-11eb-98d6-813f60129de2.png)

**Website Environment (please complete the following information):**
 - PHP Version: 8.0
 - Database driver (please include the version aswell): MySQL 5.7.34
 - Application Version: [1.2.6

**Additional context**
Although this feature isn't working/Inst released, i just saw it :/

**Comment by Morgan-Moon** [comment]
Fixed! will be in the next public release!
