### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Neko45** [tbdscripts/cosmo-issues#19]
**Describe the bug**
Achievement notification doesn't go to achievements

**Error**
Not Error/Goes to profile page

**To Reproduce**
Goto notifications then click on achievement

**Expected behavior**
Goto /achievemnts

**Screenshots**
N/A

**Website Environment (please complete the following information):**
 - PHP Version: 8.0
 - Database driver (please include the version aswell): MySQL 5.7.34
 - Application Version: [1.2.6

**Additional context**
Not really a bug but :/

**Comment by mexdeloo** [comment]
That should be the expected behavior, so we'll add it to the next release
