### ISSUE TITLE
[web] Stripe payment getting wiped

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#2]
**Describe the bug**
Stripe method payment **get wiped if not updated** when **saving settings** related to Store.
It seems that the Stripe Payment method dropdown send a blank data when it is not updated.

**Error**
**No error available** _(except the No payment method have been set when trying to checkout)_

**To Reproduce**
Steps to reproduce the behavior :
1. Go to **Settings > Store**
2. Click on **Save settings**
3. Scroll down to **Stripe accordion**
4. See that **Nothing selected** appears

**Expected behavior**
Stripe payment method **must stay saved** even if we don't update it.

**Screenshots**
**Default :** 
![image](https://user-images.githubusercontent.com/64563384/117892431-fd665200-b2b8-11eb-988e-db167fe4091a.png)

**After a Save settings if not updated :** 
![image](https://user-images.githubusercontent.com/64563384/117892460-0b1bd780-b2b9-11eb-8ee8-e4c143e62e8f.png)

**After a Save settings if updated :** 
![image](https://user-images.githubusercontent.com/64563384/117892478-17a03000-b2b9-11eb-80b0-01a201c80274.png)

**Website Environment (please complete the following information):**
 - PHP Version: **8.0**
 - Database driver : **10.2.37-MariaDB-log-cll-lve - MariaDB Server**
 - Application Version: **1.2.5**

**Comment by mexdeloo** [comment]
Value wasn't being set by default, only on change. Has been resolved now.
