### ISSUE TITLE
Notification 404

### ISSUE THREAD

**Issue by Neko45** [tbdscripts/cosmo-issues#20]
**Describe the bug**
When someone likes your profile and you click on the notification, you get sent to a 404 page.

**Error**
404 not found

**To Reproduce**
Get someone to like your profile,
Goto Notifcation, click on it.

**Expected behavior**
Lead to the users profile. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24734120/121534036-c0e15f80-c9f8-11eb-8cd3-15bb20bd7f9d.png)
![image](https://user-images.githubusercontent.com/24734120/121534078-cb035e00-c9f8-11eb-9557-e0c591b9e1df.png)

**Website Environment (please complete the following information):**
 - PHP Version: 8.0
 - Database driver (please include the version aswell): MySQL 5.7.34
 - Application Version: [1.2.6

**Additional context**
Happened since install

**Comment by Morgan-Moon** [comment]
Fixed.. Will be in the next public release!
