### ISSUE TITLE
Small issue with Move dropdown sorting

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#21]
**Describe the bug**
The move topic dropdown doesn't follow correctly the real structure of the boards / categories.
It seems that it's sorted based on some ID / creation date which may lead to confusion.

**To Reproduce**
1. Go to your Dashboard and setup some boards & categories
2. Add a new board & concatenate it into an existing one _(make sure that it's not at the last place tho)_
3. Go to Forums page & find a topic
4. Click the Move button and notice that it'll appear at the end, even if it should be upper in the list

**Expected behavior**

**Screenshots**
The dropdown list :
![image](https://user-images.githubusercontent.com/64563384/121585877-60234880-ca33-11eb-9bf6-14abdb945bf1.png)

The forum's structure : 
![image](https://user-images.githubusercontent.com/64563384/121586021-716c5500-ca33-11eb-8a6e-0e4fdd0582e0.png)

**Website Environment (please complete the following information):**
 - PHP Version: 8.0
 - Database driver (please include the version aswell): MariaDB 10.2.37
 - Application Version: 1.2.7

**Comment by Morgan-Moon** [comment]
I've been trying to find a way to make this dropdown clearer for ages. there's just nothing I can do at the moment. Once I find a solution it will be implemented!
