### ISSUE TITLE
Russian language support for cosmo.

### ISSUE THREAD

**Issue by R0MAKIM** [tbdscripts/cosmo-issues#25]
**Describe the feature you'd like to see in Cosmo.**
Adaptation of cosmo for the Russian community

**Give examples of the feature (screenshots, etc.). If applicable.**
![image](https://user-images.githubusercontent.com/85413452/122078967-2da88f80-ce27-11eb-9542-8f5b1f2a6086.png)

**Are there any alternatives for this feature? If so, list them here.**
-

**Additional context**
[rutranslate.zip](https://github.com/tbdscripts/cosmo-issues/files/6656782/rutranslate.zip)

I have translated cosmo into Russian and would like to share this translation with you.
(so to speak make a small contribution)

**Comment by mexdeloo** [comment]
Will be added in the next release!
