### ISSUE TITLE
changelogs git support

### ISSUE THREAD

**Issue by Lythium4848** [tbdscripts/cosmo-issues#27]
**Describe the feature you'd like to see in Cosmo.**
Git support for changelogs

**Give examples of the feature (screenshots, etc.). If applicable.**
shows git commits in the changelogs

**Are there any alternatives for this feature? If so, list them here.**
maybe

thx no problem

**Comment by mexdeloo** [comment]
Not enough people will use this

**Comment by LucaTanks** [comment]
A GitHub action that pushes release notes to Cosmo 🧠
