### ISSUE TITLE
ToS - Different Theme

### ISSUE THREAD

**Issue by Neko45** [tbdscripts/cosmo-issues#28]
**Describe the bug**
When going to the Store TOS, the them is different to the one activated on the main site, and I don't see an option to change it anywhere.

**Error**
ToS theme is not the same as the main sites.

**To Reproduce**
https://yourdomain/store/tos

**Screenshots**
![image](https://user-images.githubusercontent.com/85688845/122689061-029fb080-d218-11eb-8617-986a91fa3c52.png)
![image](https://user-images.githubusercontent.com/85688845/122689071-07fcfb00-d218-11eb-8a55-30aae4f485f0.png)

**Website Environment (please complete the following information):**
PHP Version: 8.0
Database driver (please include the version aswell): MySQL 5.7.34    (Not sure, just used the one from previous error that I did - My dev did that last time)
Application Version: [1.2.8]

**Additional context**
None.

**Comment by mexdeloo** [comment]
Fixed the main bug, @Morgan-Moon will still have to fix the styling and remove the retarded arrow animation on the Havart theme

**Comment by mexdeloo** [comment]
Will be fixed in next release

**Comment by mexdeloo** [comment]
Actually, fixed it myself so it's done right

**Comment by stubbo** [comment]
This is not done right you used a id rather than class idiot

**Comment by mexdeloo** [comment]
Look at the rest of the code, that's how @Morgan-Moon does it. While that's not how it's meant to be done
Just following his shit

**Comment by stubbo** [comment]
> so it's done right

**Comment by mexdeloo** [comment]
Ok stubbo
