### ISSUE TITLE
[web] Store setting's accordions not displaying properly

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#3]
**Describe the bug**
Sometimes, store setting's accordions doesn't display properly which may cause some settings not being configurable.
First accordion seems to always have this problem which makes it unconfigurable _(in my case, Stripe)_ & seems to be the origin of this bug.

**Error**
_No error as it is visual._

**To Reproduce**
1. Go to **Settings > Store**
2. Notice that **Stripe accordion** only display **Payment method** _(or your first accordion)_
3. Click on **PayPal / Store / Misc accordion** and notice that they are displayed **properly**
4. Click on **Stripe accordion** _(or the first one in the list)_
5. Then **click on another one** and notice that it **isn't displayed properly anymore**
6. Re-click **on the exact same one** and notice that it is now displayed **correctly**

**Expected behavior**
Store's accordions **working correctly** just like Integration & General ones, **fully displaying available fields**.

**Screenshots**
[Stripe accordion on initial load](https://paste.pics/383b0843d08195b778783a7dca3ced36)
[A bugged accordion](https://paste.pics/b3c3132d87b33102266055c37afbe3aa)
[A normal accordion](https://paste.pics/5ba4aafa0538a4f35f06a522bee855af)

**Website Environment (please complete the following information):**
 - PHP Version: **8.0**
 - Database driver (please include the version as well): **10.2.37-MariaDB-log-cll-lve - MariaDB Server**
 - Application Version: **1.2.5**

**Comment by mexdeloo** [comment]
I can't seem to reproduce this. Which browser are you using, maybe the issue lies there.
A video with the reproduction would be helpful as well.

**Comment by dotCore-off** [comment]
I was using Edge in it's latest version at that time.
Seems that this was on my end since this is now fixed & displayed correctly, thanks for the help.
