### ISSUE TITLE
Packages Broken with Sale

### ISSUE THREAD

**Issue by Neko45** [tbdscripts/cosmo-issues#31]
**Describe the bug**
People are trying to purchase a package (that is £6.40 - due to a sale of 20%) and its creating an error for them (paypal), however when the price is changed to £6.50 or £7, it works fine? 

**Error**
Error 500 - "You're seeing this error because something went wrong in the backend of cosmo."

**To Reproduce**
1. https://hyponixnetworks.com/store/checkout/14?
2. Attempt to "purchase via paypal"
3. See that it creates an error

**Screenshots**
![image](https://user-images.githubusercontent.com/85688845/123679572-89b7de80-d83f-11eb-8a9a-4ddc8cc3cb42.png)

**Website Environment (please complete the following information):**
 - PHP Version: [8.0]
 - Database driver (please include the version aswell): [MySQL 5.7.34]
 - Application Version: [1.2.8]

**Comment by Neko45** [comment]
its the same with all packages that arent .5 or a full numbered price
the sale messes things up, should fix this

**Comment by mexdeloo** [comment]
Just tried to replicate this (with the same price and sale), however PayPal let's me purchase this just fine. Perhaps this is a setting in the PayPal dashboard?

**Comment by mexdeloo** [comment]
Closing as I haven't been able to reproduce this, neither has the issue come across someone else.
