### ISSUE TITLE
[FEAT] webhook triggers

### ISSUE THREAD

**Issue by FelixKLG** [tbdscripts/cosmo-issues#39]
### Description of the feature

actions taken by users can trigger webhooks.

### Examples of the feature

a forum post can trigger a Discord webhook.
same with changelogs and new users (and others)

### Alternatives for the feature

this is a stupid box
make not mandatory

### Additional Context

say I was to post a new chnagelog update, it would be nice if I were able to send it to my Discord automatically though a webhook triggered by Cosmo.

**Comment by LucaTanks** [comment]
Alternatives: Ember has this

**Comment by FelixKLG** [comment]
shut up, bad stupid dumn. that's a shit way to word alternatives then retard

**Comment by stubbo** [comment]
`examples` 🙃

**Comment by FelixKLG** [comment]
shut up I tired and layzey. 
I DM'd you explaing it earlier so :shut:

**Comment by stubbo** [comment]
my comment was more aimed at the guy who made the template 👀

**Comment by FelixKLG** [comment]
![image](https://user-images.githubusercontent.com/44820580/130501658-83d72b69-49a6-453b-966e-43a70510f16d.png)

**Comment by LucaTanks** [comment]
alternative solutions or products both count tbh

**Comment by LucaTanks** [comment]
![Uploading 8BB35D33-E683-4B22-9A3A-9776BEB67C12.png…]()

**Comment by LucaTanks** [comment]
Zeo made it 😄

**Comment by FelixKLG** [comment]
shut face hole filthy ginger man

**Comment by LucaTanks** [comment]
I just copied over

**Comment by mexdeloo** [comment]
Implemented in 1.4.0
