### ISSUE TITLE
[web] Issues with some usernames

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#4]
**Describe the bug**
Arabic characters aren't displayed properly in some website's tables.
Also, there's no length verification which may lead to unexpected visual behaviors on website.

**To Reproduce**
1. Change **a user's name to ﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽** for example
2. See that it displays **correctly** on **user's table in Management**
3. Go to the **Store page**
4. Change your theme to either **Dxrk / Havart / Lara**
5. See that it doesn't display **properly** in Top / Recent donations and that it causes some trouble if name's length is too long
6. Change to **Purity** and see the expected behavior

**Expected behavior**
Arabic characters & other symbols should display in a **condensed** mode.
Also, there should be a name length verification to avoid unexpected visuals.

**Screenshots**
**Correct display :** 
![image](https://user-images.githubusercontent.com/64563384/117895227-39e87c80-b2be-11eb-8085-918694488034.png)

**Incorrect one :** 
![image](https://user-images.githubusercontent.com/64563384/117895244-4240b780-b2be-11eb-8924-bf7990146e00.png)

**Visual issue's example :** 
[Screenshot](http://upload.dotcore-lab.net/zf4Vc)

**Website Environment (please complete the following information):**
 - PHP Version: **8.0**
 - Database driver (please include the version aswell): **10.2.37-MariaDB-log-cll-lve - MariaDB Server**
 - Application Version: **1.2.5**

**Comment by mexdeloo** [comment]
I guess this is not particularly an issue with the special characters, but rather that longer usernames bug out on certain pages?

**Comment by dotCore-off** [comment]
Yep indeed, this is more about username's length than characters (just shown that some symbols could easily make it grows).
