### ISSUE TITLE
[BUG] Users unable to edit their own posts

### ISSUE THREAD

**Issue by jakkee** [tbdscripts/cosmo-issues#42]
### Description of the bug

Users are unable to edit their own post.

Screenshots from luccaa#2856 in discord (Posting here as this will probably get lost on discord)
![image0](https://user-images.githubusercontent.com/8985673/131761917-e47d6b93-eba1-4225-96f6-9f4535391b7e.png)
![image1](https://user-images.githubusercontent.com/8985673/131761928-043fdd36-7f6b-421e-9855-c8028df8f0e6.png)

### Expected Behaviour

To edit ;)

### How do you reproduce this bug?

Post any thread or comment and it'll give you an error if you try and edit.
https://ogroleplay.net/

### Website Environment

- PHP Version: 7.4
- MariaDB 10.2.40
- Application Version: 1.2.11

**Comment by JackGamesFTW** [comment]
We was trying to replicate this before but wasn't able to. We are thinking that it is a host issue but I don't have an idea of what causes it yet.

**Comment by jakkee** [comment]
Just done a quick test. If the role has "Manage Threads" ticked it will let you edit.
But if its unticked you get the 403 - Unauthorised Access

**Comment by mexdeloo** [comment]
Just tried to replicate this again but haven't been able to. I can edit my own post, with or without "Manage Threads" permission.
To be clear, I tried on the havart theme aswell.

**Comment by mexdeloo** [comment]
Fixed, will be in next release.
