### ISSUE TITLE
hidden board

### ISSUE THREAD

**Issue by Patouuu** [tbdscripts/cosmo-issues#46]
### Description of the feature

Hello, I find it cool to let people be able to create hidden panels as they want (basic we have two but now it's better to be able to create them ourselves

### Examples of the feature

Just add a feature with the possibility of creating them, nothing to complicate, a lot of cms offer it

### Alternatives for the feature

/

### Additional Context

/

**Comment by mexdeloo** [comment]
Could you elaborate more on this, not clear what you're asking.

**Comment by JoshJOkayguy** [comment]
I believe he means private boards that only certain roles can see

**Comment by mexdeloo** [comment]
Duplicate of #32
