### ISSUE TITLE
Cant remove old staff from home page

### ISSUE THREAD

**Issue by LuckyGoose1** [tbdscripts/cosmo-issues#49]
### Description of the bug

https://gyazo.com/86417405a0ee5fc4117d0e15b0e13de2

I cant update or tags to say what ranks we are and cant remove old staff.

### Expected Behaviour

Was wondering if you could explain or help me remove them and update the issue please.

### How do you reproduce this bug?

We removed the old staff members from their staff ranks but on the home page, it says they are still superadmin and also all 4 current people on the home page are saying they are superadmin but their website ranks are diffrent.

### Website Environment

- PHP Version: [e.g. 7.4]
- Database driver (please include the version aswell): [e.g. MySQL 5.8, MariaDB 10.6]
- Application Version: [e.g. 1.2.5]

**Comment by Lythium4848** [comment]
Have you tried clearing cache?

**Comment by JackGamesFTW** [comment]
Not a bug. Use the discord for this stuff.

**Comment by LuckyGoose1** [comment]
im new to this sorry one sec

**Comment by LuckyGoose1** [comment]
Thanks you Lythium4848 i got it fixed now
