### ISSUE TITLE
[web] Havart server failed image not scaling properly

### ISSUE THREAD

**Issue by zeo** [tbdscripts/cosmo-issues#5]
**Describe the bug**
When the application is unable to retrieve information about an Index Server, it shows a fallback image. The default one does not size properly on the Havart Landing Page. 

**To Reproduce**
1. Create an Index Server with an IP and port that doesn't point towards a Garry's Mod or Rust server.
2. Go to the Home/Landing page.
3. Scroll down to the server section.
4. See the image does not scale properly.

**Expected behavior**
The image should size in the same fashion as the other images of servers which do successfully have data. 

**Screenshots**
[Issue](https://user-images.githubusercontent.com/54897974/117978609-5c1be200-b332-11eb-9659-daf6a887b78c.png)

**Comment by Morgan-Moon** [comment]
I have not changed the size of the image, however I've just fixed the positioning of all of the elements ontop of the image

**Comment by mexdeloo** [comment]
Would probably look better to scale the size to the same size as the other ones, however not urgent atm so closing this.
