### ISSUE TITLE
Stuck Install Screen

### ISSUE THREAD

**Issue by KingDeadwood** [tbdscripts/cosmo-issues#56]
### Description of the bug

After installing all the files and having all options enabled the continue button will not allow me to go onto the file permissions section. 

### Expected Behaviour

To be able to go to the file permissions section of install.

### How do you reproduce this bug?

Clicking continue on the application requirements section of the install.

### Website Environment

- PHP Version: [e.g. 7.4]
- Database driver (please include the version aswell): [e.g. MySQL 5.8, MariaDB 10.6]
- Application Version: [e.g. 1.2.5]
I used nfoservers I dont know the specifics.

**Comment by LucaTanks** [comment]
**This is not a bug**
Please go to the Discord for support
