### ISSUE TITLE
Rank Sync 

### ISSUE THREAD

**Issue by Andrew-fuse** [tbdscripts/cosmo-issues#58]
### Description of the feature

Basic feature where Cosmo has an in-game integration with ULX/ SAM or a admin mod and you can sync Certain Ranks Such as Bans so people with Banned Cosmo role can only do certain things and to prevent Abuse of forums

### Examples of the feature

Somewhat like Babl had integration

### Alternatives for the feature

N/A

### Additional Context

N/a

**Comment by LucaTanks** [comment]
Duplicate of #43
