### ISSUE TITLE
[web] Not being able to clone any package

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#6]
**Describe the bug**
When attempting to **clone a package** during the creation of the new one, it just **throws an error** without cloning anything.

**To Reproduce**
1. Go to **Dashboard > Packages > Create package**
2. Click on **Clone Package**
3. Select **any existing one**
4. **See error**

**Expected behavior**
Package should be **cloned correctly** with most of the datas fulfilled to **avoid doing repetitive actions** for the same type of packages.

**Screenshots**
![image](https://user-images.githubusercontent.com/64563384/118380528-ba6eec00-b5e2-11eb-9df4-bd2db2971fa8.png)

**Website Environment (please complete the following information):**
- PHP Version: **8.0**
- Database driver (please include the version aswell): **10.2.37-MariaDB-log-cll-lve - MariaDB Server**
- Application Version: **1.2.5**

**Comment by mexdeloo** [comment]
Fixed in next release
