### ISSUE TITLE
Snow/Pumpkins/Fireworks effects for chrismas,newyear & halloween

### ISSUE THREAD

**Issue by Snoopi351** [tbdscripts/cosmo-issues#60]
### Description of the feature

It would be nice to have a feature on the panel choosing random effects but also meaning full effects such as snow or christmas effects on the website.

### Examples of the feature

It would be nice to have a feature on the panel choosing random effects but also meaning full effects such as snow or christmas effects on the website.

### Alternatives for the feature

It would be nice to have a feature on the panel choosing random effects but also meaning full effects such as snow or christmas effects on the website.

### Additional Context

It would be nice to have a feature on the panel choosing random effects but also meaning full effects such as snow or christmas effects on the website.

**Comment by LucaTanks** [comment]
Moved to internal roadmap
