### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by alexkirs** [tbdscripts/cosmo-issues#61]
### Description of the feature

We need static pages where you can put custom content with html or markup. Some payment systems require site to have privacy police page etc.

### Examples of the feature

Privacy policy page

**Comment by LucaTanks** [comment]
we usually markdown rather than up

**Comment by Lythium4848** [comment]
> Privacy policy page
A privacy policy page could easily be implimented the same way as the ToS is at the moment

**Comment by alexkirs** [comment]
> Privacy policy page
> A privacy policy page could easily be implimented the same way as the ToS is at the moment

What is the link to ToS page? I don't see it in our installation as well as on DEMO site.

**Comment by Lythium4848** [comment]
domain/store/tos

**Comment by LucaTanks** [comment]
Edits to Cosmo do void our support policy, just to inform you

**Comment by mexdeloo** [comment]
Done, will be implemented in 1.6.0
