### ISSUE TITLE
Server Colour is put twice in the edit server panel

### ISSUE THREAD

**Issue by WEEZOOKARP** [tbdscripts/cosmo-issues#63]
### Description of the bug

![image](https://user-images.githubusercontent.com/76672483/145324182-ef8cc905-9199-4a42-aa50-798cbd070cc9.png)
![Uploading image.png…]()

### Expected Behaviour

Instead of that being server colour it should probably say something like game

### How do you reproduce this bug?

I looked at the server edit panel

### Website Environment

- PHP Version: Unknown but most likely latest
- Database driver 10.4.22-MariaDB
- Application Version: 1.3.1

**Comment by Morgan-Moon** [comment]
Fixed on next update
