### ISSUE TITLE
Cannot change color of Bulleted/Numbered List

### ISSUE THREAD

**Issue by Regrave** [tbdscripts/cosmo-issues#68]
### ❌ Description of the bug

When creating a list with numbers/bullets, you cannot change the color of them. This is an issue because on some themes it causes them to not be visible. They're not selectable at all.

### ✔ Expected Behaviour

The lists to be selectable and having the ability to change their color.

### ✨ How do you reproduce this bug?

I'm able to reproduce this consistently every time. It personally first happened when I attempted to create a static page and tried to use the numbered list markdown.

### 🌳 Website Environment

- PHP Version: 7.4
- Database driver (please include the version aswell): MySQL 5.8
- Application Version: 1.6.0

### 📋 Additional Information

I did not get an error. I can upload images/a video if it is not reproduceable on your end as well.

**Comment by LucaTanks** [comment]
Coming with new text editor (on internal roadmap)
