### ISSUE TITLE
[web] Like's count not working on some profile's tabs

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/cosmo-issues#7]
**Describe the bug**
It seems that on **Threads & Achievements tabs**, Like's count **doesn't work**.
Also if you try clicking on it _(so editing the var)_, it'll display a NaN instead of the real number.

**To Reproduce**
1. **Go to a user's profile**
2. **Set your theme** to either **Havart / D4rk / Lara** _(as Purity only display it on Home page)_
3. **Click on the like** and notice that it works
4. **Switch to threads or achievements tabs **
5. Notice that **it doesn't display any number / animation** _(fa-gold_anim)_
6. **Click on it** and notice that it now displays **NaN**

**Expected behavior**
Like's count **should appear correctly** on all profile's tabs & **should be editable** everywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/64563384/118484258-51d55b80-b717-11eb-9d09-30badf293258.png)

**Website Environment (please complete the following information):**
- PHP Version: **8.0**
- Database driver (please include the version aswell): **10.2.37-MariaDB-log-cll-lve - MariaDB Server**
- Application Version: **1.2.5**

**Comment by mexdeloo** [comment]
Fixed in next release
