### ISSUE TITLE
Bug shop

### ISSUE THREAD

**Issue by Zozoar-Configuration** [tbdscripts/cosmo-issues#74]
### ❌ Description of the bug

When I want to pay with stripe or paypal, it doesn't work even though I have configured the 2 normally as indicated on the presentation video

### ✨ How do you reproduce this bug?

I encountered the bug when configuring the shop

### 🌳 Website Environment

- PHP Version: 7.4
- Database driver (please include the version aswell): MySQL 5.8
- Application Version: 1.7.2

**Comment by LucaTanks** [comment]
You need to join the Discord for support. This is a bug reporting area

**Comment by Zozoar-Configuration** [comment]
> You need to join the Discord for support. This is a bug reporting area

I'm already on the discord but I don't really understand what to do : Zozoar#0901
