### ISSUE TITLE
Store credits

### ISSUE THREAD

**Issue by WelshBanana** [tbdscripts/cosmo-issues#78]
### 💡 Description of the feature

It would be nice to see the ability to have store credit through the stove function karma some people nearly want to donate to community and don't yet want to buy a package therefore it's a good idea to introduce credits so players can buy them instead of a package and then later if they want to they can then purchase a package using said credits, money or a combination of the both. 

### ❗ Examples of the feature

N/A

**Comment by mexdeloo** [comment]
100th duplicate
