### ISSUE TITLE
Thread says locked when it is not

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#8]
**Describe the bug**
I went to a staff app in my community forum. Where it said locked. I pressed to read the post and then it says it is normal. I jumped back out and reloaded the page to double check no one locked it for 1 sec. That was not the case.

**To Reproduce**
1. Go to the board where something was posted. Then it would be as "screenshots".

**Expected behavior**
Not to say locked at all.

**Screenshots**
https://gyazo.com/b39603a834328906c4aa0b09a6bf57c2
https://gyazo.com/bc72096cf6868f9f239efd339fa8865a

**Comment by mexdeloo** [comment]
Can't seem to reproduce this issue
