### ISSUE TITLE
Sync with gmod bug

### ISSUE THREAD

**Issue by ghost** [tbdscripts/cosmo-issues#85]
### ❌ Description of the bug

When I put the "cosmo_gmod" folder in my addons this problem appear : 

[Cosmo - DEBUG] Checking for pending orders... L 04/17/2022 - 00:12:07: Lua Error: [cosmo_gmod] addons/cosmo_gmod/lua/cosmo/core/sv_database.lua:58: attempt to index field 'con' (a nil value) 1. escape - addons/cosmo_gmod/lua/cosmo/core/sv_database.lua:58 2. getPendingOrders - addons/cosmo_gmod/lua/cosmo/core/sv_database.lua:35 3. checkForPendingOrders - addons/cosmo_gmod/lua/cosmo/core/sv_core.lua:4 4. func - addons/cosmo_gmod/lua/cosmo/core/sv_core.lua:116 5. unknown - lua/includes/modules/hook.lua:241

### ✨ How do you reproduce this bug?

To reproduce the bug I have to enter my MYSQL credentials in "sv_config.lua" and relaunch my server.

### 🌳 Website Environment

- PHP Version: 7.4
- Database driver : MariaDB 10.3.31
- Application Version: 1.2.5

**Comment by Lythium4848** [comment]
@Ahoyas You are using an out of date version of the cosmo-gmod addon. Please update it from [here](https://github.com/tbdscripts/cosmo-gmod/releases/tag/2.0.1)

**Comment by Lythium4848** [comment]
Also you do not have the MySQLoo module installed to your server

**Comment by LucaTanks** [comment]
Not a bug, use the Discord for support.
