### ISSUE TITLE
Cosmo Sale Bug

### ISSUE THREAD

**Issue by Karoffel9206** [tbdscripts/cosmo-issues#86]
### ❌ Description of the bug

Whenever I try to place a test order, the same error comes up again and again. It doesn't matter whether the price is €6.00 ​​or €6.56, the same error always occurs.

### ✨ How do you reproduce this bug?

1. Go to http://deltanix.tk/store/servers/1
2. Try to buy a package
3. Attempt to "purchase via paypal"
4. See the Problem 
A picture of the Error
[https://i.imgur.com/noSWtEm.png](url)

### 🌳 Website Environment

- PHP Version: [e.g. 8.0]
- Database driver (please include the version aswell): [e.g. MySQL 5.8]
- Application Version: [e.g. 1.2.8]

**Comment by LucaTanks** [comment]
Please report errors in the Discord first, as it may not be a bug and more of a configuration error
