### ISSUE TITLE
Payment Idea

### ISSUE THREAD

**Issue by Davidbp99** [tbdscripts/cosmo-issues#9]
**Describe the feature you'd like to see in Cosmo.**
Add so different packages go to different founders. Example as superior cwrp and milrp donations goes to Scott. While darkrp, zombie, and the other donations to aStonedPenguin. Other communities that got the same setup would love this.

**Give examples of the feature (screenshots, etc.). If applicable.**
Prometheus got something like this in packages settings (I don't have the addon so can't show it)

**Are there any alternatives for this feature? If so, list them here.**
Instead of filling in the same details over and over again in each package. You can make it so you can have multiple store settings and then name it something. Example: SWRP Owner (donation money goes to their PayPal, stripe etc), MilRP Owner (donation money goes to their PayPal, stripe etc)

Then in the package, you can select 1 or 2. If the system only finds one setting then it will auto select that to not be a pain to people that just got one founder instead of 2, 3, or 4 founders

**Comment by LucaTanks** [comment]
Moved to internal roadmap
